In [1]:
import numpy as np


In [2]:
#creating a 1-D array
x=np.array([1,2,3,4,5])
#printing array
print(x)

[1 2 3 4 5]


In [4]:
#creating a 2-D array
x=np.array([[1,2,3],[4,5,6]])
#printing array
print(x)

[[1 2 3]
 [4 5 6]]


In [7]:
#creating a 1-D zeros array
x=np.zeros([5])
print(x)

[0. 0. 0. 0. 0.]


In [9]:
#creating a 1-D ones array
x=np.ones([5])
print(x)

[1. 1. 1. 1. 1.]


In [10]:
x=np.array([1,2,3])
y=np.array([1,2,3])
#addition of two numbers
z=x+y
print(z)

[2 4 6]


In [19]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([[1,2,3],[1,2,3]])
#multiplication of two numbers
z=x*y
print(z)

[[1 4 9]
 [1 4 9]]


In [18]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([1,2,3])
#dot product of two numbers
z=np.dot(x,y)
print(z)

[14 14]
